version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  magneto-api:
    image: magneto-api-image
    ports:
      - 8080:8080
    links:
      - mongodb